sources:
  - name: staging
    schema: staging
    tables:
      - name: yellow_tripdata_2023_01
        freshness:
          warn_after: {count: 90, period: day}
          error_after: {count: 180, period: day}
